### ISSUE TITLE
Comentarios sobre el ejercicio

### ISSUE THREAD

**Issue by m4n50n** [INVIiICTUS/Traffic-Light-with-React-2.0#1]
Hola Quique,

muy bien el ejercicio. El resultado es exactamente el que se pide.

Para la próxima, sí que te animo a intentar reducir más el código con la finalidad de que sea más automático.

Bastaría con tener un array con los colores posibles del tipo `const colores = ["rojo", "amarillo", "verde"]` y un hook de estado del tipo "colorSeleccionado", que irá cambiando onClick, de forma que en el return renderices todos los elementos en base al array colores con un map comparando ese color con el seleccionado.

Si tienes alguna duda pregúntanos sin problemas.

**Comment by INVIiICTUS** [comment]
Genial, me lo apunto
